/* Auto-generated by unplugin-vue-router. Do not edit manually. */
declare module 'vue-router/auto-routes' {
  import type { RouteRecordRaw } from 'vue-router'
  export const routes: RouteRecordRaw[]
}
declare module 'vue-router/auto' {
  import type { Router, RouteLocationNormalizedLoaded, RouteRecordRaw } from 'vue-router'
  export function createRouter(options: any): Router
  export const useRoute: () => RouteLocationNormalizedLoaded
  export const useRouter: () => Router
}
