/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin-appeal': RouteRecordInfo<
      '/admin-appeal',
      '/admin-appeal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin-rules': RouteRecordInfo<
      '/admin-rules',
      '/admin-rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/friends': RouteRecordInfo<
      '/friends',
      '/friends',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/leaderboard': RouteRecordInfo<
      '/leaderboard',
      '/leaderboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/probe': RouteRecordInfo<
      '/probe',
      '/probe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/record-submit': RouteRecordInfo<
      '/record-submit',
      '/record-submit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verdict': RouteRecordInfo<
      '/verdict',
      '/verdict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.page.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin.page.vue': {
      routes:
        | '/admin'
      views:
        | never
    }
    'src/pages/admin-appeal.page.vue': {
      routes:
        | '/admin-appeal'
      views:
        | never
    }
    'src/pages/admin-rules.page.vue': {
      routes:
        | '/admin-rules'
      views:
        | never
    }
    'src/pages/friends.page.vue': {
      routes:
        | '/friends'
      views:
        | never
    }
    'src/pages/leaderboard.page.vue': {
      routes:
        | '/leaderboard'
      views:
        | never
    }
    'src/pages/login.page.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/probe.page.vue': {
      routes:
        | '/probe'
      views:
        | never
    }
    'src/pages/record-submit.page.vue': {
      routes:
        | '/record-submit'
      views:
        | never
    }
    'src/pages/register.page.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/verdict.page.vue': {
      routes:
        | '/verdict'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
